version: '2.1'

services:
  rd-commondata-api-db:
    build:
      context: database
    image: hmcts/rd-commondata-api-db
    container_name: rd-commondata-api-db
    volumes:
      - rd-commondata-api-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-dbrdcommondata}"
    ports:
      - 5460:5432
volumes:
  rd-commondata-api-volume:
